name: ZarvexTags
version: 1.0
main: com.zarvex.zarvextags.ZarvexTags
author: Felipe
depend: [PlaceholderAPI]

commands:
  tag:
    description: Define a tag de um jogador.
    usage: /<command> <jogador> <tag>
    permission: zarvextags.tag
  tagsreload:
    description: Recarrega as tags do arquivo de configuração.
    permission: zarvextags.reload
  tagmod:
    description: Adiciona uma tag a um jogador.
    usage: /<command> <jogador> <tag>
    permission: zarvextags.tagmod
